--- #YAML:1.0
name:               BerkeleyDB
version:            0.50
abstract:           Perl extension for Berkeley DB version 2, 3, 4 or 5
author:
    - Paul Marquess <pmqs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
